### ISSUE TITLE
How to restrict alert types to just success, warning and error?

### ISSUE THREAD

**Issue by StarAzure** [vishaltelangre/editorjs-alert#1]
thanks for the useful library.

How to allow just success, warning and error without forking the library?

**Comment by vishaltelangre** [comment]
@StarAzure Thanks. 

It's not possible at this moment. But I would like to have a configuration to control the alert types. If you are up for a challenge, try sendinng a PR to make it configurable.

The option should allow the consumer of this library to override the alert types while integrating it.

If you are not able to do that, I will do it some time later in this month.

**Comment by StarAzure** [comment]
I just converted your plugin to a local plugin and removed the additional alerts to support material ui theme. I had to do that to support various alert styles from material ui such as contained, outlined etc so it was easier.
I am afraid I have customized it too much to be included as a PR.
