### ISSUE TITLE
Tune box too short

### ISSUE THREAD

**Issue by morsecoding** [vishaltelangre/editorjs-alert#18]
The tune box is too short and causes the delete and move buttons to be crowded out and hard to see. You can scroll them if you hover over but should either show all at once or scroll the entire tune box, not just move and delete. If vertical space is a constraint, making the alert color selections smaller so they fit 4 across would be a better option.
<img width="218" alt="image" src="https://user-images.githubusercontent.com/5273301/221641470-a9fba8b7-7d81-481f-9162-4162a629bee2.png">

**Comment by vishaltelangre** [comment]
Should be fixed in the latest v1.1.2.
