### ISSUE TITLE
Feature Request - Text Justify

### ISSUE THREAD

**Issue by calumk** [vishaltelangre/editorjs-alert#20]
I would really like the ability to "Left / Center / Right" Justify text in the alert box

Specifically centering would be ideal for my use case, but might as well support all 3.

Would you have time to add this, or be willing to accept a PR with this implemented?

**Comment by vishaltelangre** [comment]
> or be willing to accept a PR with this implemented?

I will be more than happy to accept a PR for that. Thanks for your interest!

**Comment by calumk** [comment]
PR : https://github.com/vishaltelangre/editorjs-alert/pull/21

**Comment by calumk** [comment]
Closed with merge of #21
