### ISSUE TITLE
Choose the allowed alert types

### ISSUE THREAD

**Issue by collimarco** [vishaltelangre/editorjs-alert#22]
It would be nice to have an option (a config param like `allowedTypes`) to choose what alert types we want to show in the editor.

e.g. sometimes you don't want to allow the user to add a "Danger" alert.

**Comment by vishaltelangre** [comment]
Please feel free to send a PR.

**Comment by calumk** [comment]
Some things to consider: 

Should `allowedTypes` also prevent rendering non-allowed types ?

For example, if the block is already set to "Danger" and is loaded, but the 'allowedTypes' doesnt include "Danger" what happens?

a) Does it render anyway? 
b) Does it show an error "Alert cannnot be displayed etc" 

---

I would assume for backwards-compatibility, that if allowedTypes is not defined, then all types should be allowed by default.

**Comment by collimarco** [comment]
> a) Does it render anyway?

Yes (usually you don't want to lose any content).

You can simply assign a default (like `primary` or `info` which are quite neutral in their meaning).

> b) Does it show an error "Alert cannnot be displayed etc"

No (it would be a nightmare)

> if allowedTypes is not defined, then all types should be allowed by default

Yes, I think it's the best solution.

**Comment by collimarco** [comment]
> Please feel free to send a PR.

@vishaltelangre I sent a pull request: it's a simple modification, but it adds a lot of flexibility to this plugin. Can you merge it please? Let me know if you need something else
